In [1]:
print('假設跑步為a，跳繩為b')
a_mean=25
b_mean=10
a_std=2.3
b_std=5.9
a_cv=a_std/a_mean
b_cv=b_std/b_mean
print('跑步的變異係數:',a_cv)
print('跳繩的變異係數:',round(b_cv,2) )
print('變異係數愈大代表這個團體的離散程度愈大')

假設跑步為a，跳繩為b
跑步的變異係數: 0.092
跳繩的變異係數: 0.59
變異係數愈大代表這個團體的離散程度愈大


In [3]:
import pandas as pd
import numpy as np
# 財富美國1000強
# Rank 等級
fortune = pd.read_csv("fortune1000.csv",index_col='Rank')
#print(fortune)
a=fortune['Revenue'] # 收入
b=fortune['Employees'] # 公司員工人數
print('共變異數(協方差)的推算，計算波動的程度')
print(np.cov(a,b))
print('相關係數的推算，計算兩者的相關性')
print(np.corrcoef(a,b))

共變異數(協方差)的推算，計算波動的程度
[[8.30622323e+08 1.89144910e+09]
 [1.89144910e+09 8.17716725e+09]]
相關係數的推算，計算兩者的相關性
[[1.         0.72575731]
 [0.72575731 1.        ]]


### 單位矩陣與轉置矩陣

In [6]:
import numpy as np
array1 = np.eye(4)
print(array1)
array2=np.array([[3,5,6,8],[13,25,46,98],[111,234,556,567]])
print(array2)
print(np.transpose(array2))
print(array2.T)

s = [[1,2],
     [2,1]]
s = np.array(s)
print(s)
print(s.T)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[  3   5   6   8]
 [ 13  25  46  98]
 [111 234 556 567]]
[[  3  13 111]
 [  5  25 234]
 [  6  46 556]
 [  8  98 567]]
[[  3  13 111]
 [  5  25 234]
 [  6  46 556]
 [  8  98 567]]
[[1 2]
 [2 1]]
[[1 2]
 [2 1]]


In [7]:
import numpy as np
a = [[15,14,15],
     [12,13,17]]
b = [[10,14],
    [5,18],
    [8,10]]
a = np.array(a)
b = np.array(b)
print(a.shape)
print(b.shape)
print(np.dot(a,b))
print(a@b)

(2, 3)
(3, 2)
[[340 612]
 [321 572]]
[[340 612]
 [321 572]]


In [8]:
import numpy as np
a = [[6,3],
     [8,10]]
b = [[2,1],
     [5,-3]]
a = np.array(a)
b = np.array(b)
print(a@b)
print(b@a)

[[ 27  -3]
 [ 66 -22]]
[[ 20  16]
 [  6 -15]]
