In [4]:
import requests
from bs4 import BeautifulSoup
url = "https://zh.wikipedia.org/zh-tw/2023年电影"
resp = requests.get(url)
resp.encoding = "utf-8"
#print(resp.text)
soup = BeautifulSoup(resp.text,'html5lib')
moveTable = soup.find("table",class_ = "wikitable")
tbody = moveTable.find("tbody")
trList = tbody.find_all("tr")
for inx in range(1,len(trList)):
    print(trList[inx].find("th").text.strip())
    print(trList[inx].select_one("a").text.strip())
    print(trList[inx].find_all("td")[2].text.strip())
    

1
超級瑪利歐兄弟電影版
$1,359,332,753
2
Barbie芭比
$1,340,301,000
3
星際異攻隊3
$845,512,122
4
奧本海默
$777,198,260
5
玩命關頭X
$704,709,660
6
蜘蛛人：穿越新宇宙
$687,913,244
7
滿江紅
$673,556,758
8
流浪地球2
$604,456,556
9
小魚仙
$568,599,372
10
不可能的任務：致命清算 第一章
$551,963,273


# Numpy 建立與計算

In [5]:
c1 = [1,3,5,7,9]
d1 = [3,5,6,7,9]
f1 = c1 + d1
print(f1)

[1, 3, 5, 7, 9, 3, 5, 6, 7, 9]


In [7]:
import numpy as np
c2 = np.array([1,3,5,7,9])
d2 = np.array([3,5,6,7,9])
f2 = c2 + d2
print(f2)

[ 4.  8. 11. 14. 18.]


+ ndarray.ndim
   + 維度的數量。
+ ndarray.shape
   + 顯示出陣列在每個維度上的整數值。
+ ndarray.size
   + 陣列內元素的總數。
+ ndarray.dtype
   + 用來描述陣列中元素類型的對象。

In [11]:
import numpy as np
i = [[1,2,3],
     [2,3,4]]
a = np.array(i)
print(a)
print("number of dim:",a.ndim) #維度的數量 也可稱為軸的數量
print("number of shape:",a.shape)
print("size:",a.size)
print("dtype:",a.dtype)


[[1 2 3]
 [2 3 4]]
number of dim: 2
number of shape: (2, 3)
size: 6
dtype: int32


In [13]:
import numpy as np
a = np.array( [6, 7, 8, 9] )
b = np.arange(4)
c = a - b
print("a=>",a)
print("b=>",b)
print("c=>",c)
d = b**2
print("d=>",d)
f = np.array([5, -1, 3, 9, 0])
f[f<=3] = 1
print("f=>",f)

a=> [6 7 8 9]
b=> [0 1 2 3]
c=> [6 6 6 6]
d=> [0 1 4 9]
f=> [5 1 1 9 1]


In [16]:
import numpy as np
x = np.ones((2,4))
print(x)
print("-"*70)
x = np.full((2,4),6)
print(x)
print("-"*70)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
----------------------------------------------------------------------
[[6 6 6 6]
 [6 6 6 6]]
----------------------------------------------------------------------


## 陣列初始化與重新規劃
+ 針對初始化這部分提供了多種方式：
+ 不做初始化
   + 例如：np.empty((2,4))
+ 全部規劃為 0
   + 例如：np.zeros((3,4))
+　全部規劃為 1
  + np.ones((5,2))
+ 全部規劃／填滿為某數，例如 6
   + 例如： np.full((3,3),6)
+ 建立對角矩陣，對角皆為 1，其他為 0
   + 例如： np.eye(3)
+ 建立對角矩陣，對角為 1,2,3,4，其他為 0
   + 例如： np.diag([1,2,3,4])
+ reshape((x,y)) 這個指令就可以將現有的陣列  重新規劃為 x 乘以 y 的陣列。 
+ np.arange(起始值, 結束值, 固定間隔)：也是產生一維陣列，和 np.array( ) 的差別在於 arange 擁有較大的彈性，而且元素數值是自動化產生。
+ np.linspace(起始值, 結束值, 起始與結束的區間內要產生幾個元素 )：只要給定陣列的區間(起始值、結束值)，就可以要求在這個區間內產生幾個元素。
+ arange(a,b,c)
   + 不包含 b 由 a 開始 以固定間隔 c 來取值
+ linspace(a,b,c,)
   + 包含 b 由 a 開始 切割成 c 個資料
+ linspace(a,b,c,endpoint=False)
   + 不包含 b 由 a 開始 切割成 c 個資料

### empty zeros ones

In [1]:
import numpy as np
x = np.empty((2,4))
print(x)
print("-"*70)
x = np.zeros((3,4))
print(x)
print("-"*70)
x = np.ones((2,4))
print(x)

[[0.000e+000 0.000e+000 0.000e+000 0.000e+000]
 [0.000e+000 6.443e-321 0.000e+000 0.000e+000]]
----------------------------------------------------------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
----------------------------------------------------------------------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### eye diag

In [3]:
import numpy as np
x = np.eye(3)
print(x)
x = np.diag([1,2,3,4])
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


### linspace arange

In [10]:
import numpy as np
x = np.linspace(1,10,6)
print(x)
print("==============")
x = np.linspace(1,10,6).reshape((3,2))
print(x)
x = np.linspace(1,10,6,endpoint=False).reshape((2,3))
print(x)

[ 1.   2.8  4.6  6.4  8.2 10. ]
[[ 1.   2.8]
 [ 4.6  6.4]
 [ 8.2 10. ]]
[[1.  2.5 4. ]
 [5.5 7.  8.5]]


In [11]:
import numpy as np
r1 = np.arange(25, 30, .5)
print("r1=>",r1)

r1=> [25.  25.5 26.  26.5 27.  27.5 28.  28.5 29.  29.5]


In [12]:
import numpy as np
lin = np.linspace(3, 5, 9)#5-3/9-1
print("r1=>",lin)


r1=> [3.   3.25 3.5  3.75 4.   4.25 4.5  4.75 5.  ]


## 陣列指定位置取值
+ 間隔選取 [::c]
  + 以 1 維陣列來說明 x[a:b:c]
  + a：選取資料的起始索引
  + b：選取資料的結束索引 +1
  + c：選取資料間隔，以索引值可以被此值整除的元素，不指定表示 1
+ 倒序 [::-1]
  + 只是單純的把順序反過來

## 陣列指定位置-給予一個整數
+ 關於指定位置  [row,column]
+ 假設給予一個整數為 N
 + 如果是給固定的 N，那就代表 row 或 column 等於 N。
 + 如果是 N：，那就代表 row 或 column 大於等於 N 的區域。
 + 如果是：N，那就代表 row 或 column 小於 N 的區域。 
 + 如果是：，那就代表 row 或 column 是任意欄位

In [16]:
import numpy as np
a = np.array([[1,2,3],
              [3,6,9],
              [2,4,6]])
print(a)
print("================")
print(a[0])
print("================")
print(a[1,2])

[[1 2 3]
 [3 6 9]
 [2 4 6]]
[1 2 3]
9


In [21]:
import numpy as np
a = np.arange(1,10).reshape((3,3))
print(a)
print("==============================")
print(a[1,1:3])
print("==============================")
print(a[:,1])
print("==============================")
print(a)
print("==============================")
a[1,2] = 75
print("==============================")
print(a)
print("==============================")
a[:,0] = [100,101,102]
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[5 6]
[2 5 8]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4  5 75]
 [ 7  8  9]]
[[100   2   3]
 [101   5  75]
 [102   8   9]]


In [25]:
import numpy as np
a=np.arange(0,36).reshape((6,6))
print(a)
print("==1===")
print(a[0,3:5])
print("==2===")
print(a[4:,4:])
print("==3===")
print(a[:3,:3])
print("==4===")
print(a[:,2])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
==1===
[3 4]
==2===
[[28 29]
 [34 35]]
==3===
[[ 0  1  2]
 [ 6  7  8]
 [12 13 14]]
==4===
[ 2  8 14 20 26 32]


## 重設新陣列
+ resize 這個動作會依據原本的陣列再設定指定大小的新陣列。 
+ resize 動作的參數如下：
+ numpy.resize(arr1，shape1)
  + arr1：原本的陣列
  + shape1：新規劃的大小
+ 如果規劃的新陣列比較大，將會重新複製原有陣列的資料，填滿新的儲存格。
+ resize 這個動作***建立新的陣列***，而 reshape 則是依據原有的重新規劃，仍會受到原有陣列影響。
+ transpose()轉置

In [26]:
import numpy as np
a = np.array([[1,2,3],
              [4,5,6]])
print(a.shape)
print()
b = a.reshape(3,2)
print(b)
print(b.shape)
a[0,1] = 100
print(b) # 會改變
print(b.shape)
print(a.shape)

(2, 3)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[[  1 100]
 [  3   4]
 [  5   6]]
(3, 2)
(2, 3)


### resize

In [27]:
import numpy as np
a = np.array([[1,2,3],
              [4,5,6]])
print(a)
print(a.shape)
print()
b = np.resize(a,(3,2))#資料內容會複製一份
print(b)
print(b.shape)
print()
a[0,1] = 100
print(b)#不會改變
print(b.shape)
print(a.shape)
b = np.resize(a,(10,10))#resize 大於原本size
print(b)

[[1 2 3]
 [4 5 6]]
(2, 3)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
(2, 3)
[[  1 100   3   4   5   6   1 100   3   4]
 [  5   6   1 100   3   4   5   6   1 100]
 [  3   4   5   6   1 100   3   4   5   6]
 [  1 100   3   4   5   6   1 100   3   4]
 [  5   6   1 100   3   4   5   6   1 100]
 [  3   4   5   6   1 100   3   4   5   6]
 [  1 100   3   4   5   6   1 100   3   4]
 [  5   6   1 100   3   4   5   6   1 100]
 [  3   4   5   6   1 100   3   4   5   6]
 [  1 100   3   4   5   6   1 100   3   4]]


### transpose

In [29]:
import numpy as np
newArray = np.arange(10).reshape(2,5)
print("================")
print(newArray)
print("================")
print(newArray.transpose())
print("================")
print(newArray) ## 原始陣列部會改變
print("================")
tArray = newArray.T
print(tArray)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


### 總和sum()

In [30]:
import numpy as np
a = np.array([[0, 30,45],
              [60,75,90]])
print(a)
print("---------------")
b=np.sum(a)# 無選軸 每個元素相加
print(b)
print("---------------")
b=np.sum(a,axis=0) #拿row的陣列相加
print(b)
print("---------------")
b=np.sum(a,axis=1)#每個陣列的colum相加
print(b)
print("---------------")

[[ 0 30 45]
 [60 75 90]]
---------------
300
---------------
[ 60 105 135]
---------------
[ 75 225]
---------------
